apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  name: "{{ include "migrate-job.fullname" . }}-{{ .Release.Revision }}"
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "migrate-job.labels" . | nindent 4 }}
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        {{- include "migrate-job.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccount: {{ .Values.job.serviceAccount.name }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.global.accountId }}.{{ .Values.global.baseImage.repository }}:{{ .Values.global.baseImage.tag }}"
        env:
            - name: ENV_STATE
              value: {{ .Values.global.envState }}
            - name: DJANGO_SETTINGS_MODULE
              value: "config.settings.{{ .Values.global.django.settingsFile }}"
        imagePullPolicy: {{ .Values.global.baseImage.pullPolicy }}
        command: {{ .Values.job.migrateCommand }}
      restartPolicy: {{ .Values.job.restartPolicy }}
