---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
      targetPort: {{ .Values.image.containerPort }}
      protocol: TCP
  selector:
    app: {{ .Values.serviceName }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/success-codes: 200-299
    alb.ingress.kubernetes.io/healthcheck-path: /ht/
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=900
    alb.ingress.kubernetes.io/wafv2-acl-arn: {{ .Values.wafId }}
spec:
  tls:
  - hosts:
    - {{ .Values.hostName }}
  defaultBackend:
    service:
      name: {{ .Values.serviceName }}
      port:
        number: {{ .Values.service.port }}
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.serviceName }}
              port:
                number: {{ .Values.service.port }}
